### ISSUE TITLE
How to get rendered image under headless setting?

### ISSUE THREAD

**Issue by chenerg** [szabolcsdombi/zengl#32]
I want to render image without showing opengl window.

**Comment by szabolcsdombi** [comment]
Here is a headless example: https://github.com/szabolcsdombi/zengl/blob/main/examples/hello_triangle_headless.py

All the other examples can be converted to headless by:
- removing the window and the main loop
- initializing zeng.context() similar to the example above
- saving the final image instead of a blit to screen

If you render to a multisampled image, you have to blit it to a single sample image before you can read it.
You can find an example of this blit here: https://github.com/szabolcsdombi/zengl/blob/main/examples/hello_triangle_headless_multisample.py

**Comment by chenerg** [comment]
Thank you very much! That totally solves my problem.
