### ISSUE TITLE
examples README.md links to not existing pygbag folder

### ISSUE THREAD

**Issue by HubertReX** [szabolcsdombi/zengl#60]
It seems that zengl should run with pygbag, but I can't find a working example.

This [README.md](https://github.com/szabolcsdombi/zengl/blob/main/examples/README.md) has link to pygbag folder, but there is no such a folder.

**Comment by szabolcsdombi** [comment]
The example got broken due to the pygbag CDN content is changing or something else happens which makes my Containerfile build differently after a while. I am waiting on pygbag to stabilize a bit.
Currently the best way to run zengl using pygbag is:

```
pygbag --git --PYBUILD 3.12 --template=noctx.tmpl --ume_block 0 --archive .
```

https://github.com/szabolcsdombi/pyweek-36/blob/main/pygbag/main.py

Please note that `--git` refers to the part which is likely changing.

If you encounter problems please consider asking on discord https://discord.com/channels/772505616680878080/971360806287577098
pmp-p and other usually reply fast with quick solutions. This is how I do it myself.

PS: To prevent changes I use the `--archive` however it is not enough on it's own. I usually just download all the files from the network tab and ship it on itch https://szabolcsdombi.itch.io/ so no files are loaded from a remote.

**Comment by HubertReX** [comment]
Awesome! I've managed to run it. Also, I figured out how to start this example:
https://github.com/pygame-web/showroom/blob/main/src/test_zengl_debug.py

I'm really inspired by the idea of having a 2D, pixel art game using pygame-ce, combined with some postprocessing shaders with for example zengl. Running it all in the browser on GitHub pages or itch.io is just the next level 👌.

And yes, pmp-p is always quick to help, I'm already using this channel. Thanks for the tip anyway ;-) 
You can close the issue if you want.
